{"name": "test_member_address_1", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ncase\\test_member_address.py:12: AssumptionFailure\n>>\tpytest.assume(result[\"body\"][\"code\"] != 200, \"断言开发自检字段\")\nAssertionError: 断言开发自检字段\nassert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               case\\test_member_address.py:12: AssumptionFailure\nE               >>\tpytest.assume(result[\"body\"][\"code\"] != 200, \"断言开发自检字段\")\nE               AssertionError: 断言开发自检字段\nE               assert False\n\nd:\\python\\lib\\site-packages\\six.py:702: FailedAssumption"}, "description": "\n    查询别人的地址id=11\n    :return:\n    ", "start": 1615079444433, "stop": 1615079444431, "uuid": "e1d42983-a60f-4976-b860-1fe054a2f61d", "historyId": "553d2b6a98b21d4c80fc1dc55631f7ef", "testCaseId": "43cfb5b8d5a8c9abe7dcd360191e1def", "fullName": "case.test_member_address#test_member_address_1", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_member_address"}, {"name": "host", "value": "DESKTOP-BE07TO9"}, {"name": "thread", "value": "9988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_member_address"}]}