{"name": "test_update_member_address_5", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ncase\\test_update_member_address.py:145: AssumptionFailure\n>>\tpytest.assume(result[\"body\"][\"code\"] != 200, \"断言开发自检字段\")\nAssertionError: 断言开发自检字段\nassert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               case\\test_update_member_address.py:145: AssumptionFailure\nE               >>\tpytest.assume(result[\"body\"][\"code\"] != 200, \"断言开发自检字段\")\nE               AssertionError: 断言开发自检字段\nE               assert False\n\nd:\\python\\lib\\site-packages\\six.py:702: FailedAssumption"}, "description": "\n    修改收货地址信息phone_number为不正确号码\n    :return:\n    ", "start": 1615079575402, "stop": 1615079575402, "uuid": "68771b27-a985-4467-ab20-109e9ca6a4e4", "historyId": "4d5d8b24de4cc6b4eb5e94726579ea1c", "testCaseId": "b5c81feeedb82609a0a9a1d8e8d282bc", "fullName": "case.test_update_member_address#test_update_member_address_5", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_update_member_address"}, {"name": "host", "value": "DESKTOP-BE07TO9"}, {"name": "thread", "value": "9988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_update_member_address"}]}